### ISSUE TITLE
GeoDatabase Data Curation Primer

### ISSUE THREAD

**Issue by jasonbrodeur** [DataCurationNetwork/data-primers#2]
Hello, 

Just a comment on the QGIS section of the primer. While QGIS works well for vector layers in geodatabses, there seems to be no support for rasters within geodatabases. It might be helpful to mention this, as a curator will only see vectors in QGIS.

**Comment by andrewbattista** [comment]
Thanks, @jasonbrodeur - will will address this and make a clarification in the primer!

**Comment by andrewbattista** [comment]
@jasonbrodeur We made the clarification. Thank you again for pointing this out
