### ISSUE TITLE
 R Data Curation Primer - include dependency management tools

### ISSUE THREAD

**Issue by vildead** [DataCurationNetwork/data-primers#29]
Listing used packages (and their versions) is IMHO not **Best practice** any more. It is definitely "Good Enough Practice" though. 

There are several packages allowing users to capture whole package dependency tree in a simple text file and re-create the environment very easily:
- [renv](https://rstudio.github.io/renv/articles/renv.html)
- [packrat](https://rstudio.github.io/packrat/) - this one is also already integrated in RStudio
- [checkpoint](https://rstudio.github.io/packrat/)
- ...

**Comment by kekoziar** [comment]
The packages you listed will capture a list of dependencies.  By including, for example, the renv lockfile with the software that's shared, a different researcher will be able to install the dependencies (and required versions) necessary to run the scripts.  So, how is that no longer best practices?  It seems the packages you indicated help researchers list and document the packages/versions (i.e. environment) the code depends on. 

IMO, a list of dependencies is best practices. Using a package to help create that list is wonderful.  Perhaps, the primer can be annotated to include that list as tools which help document the packages in the environment.

**Comment by vildead** [comment]
@kekoziar you are right! Indeed, the list of dependencies and dependency management tool are not the same thing. I will create an MR with the list of existing tools 
Thanks
