### ISSUE TITLE
Structure Suggestion

### ISSUE THREAD

**Issue by DonRichards** [DataCurationNetwork/data-primers#36]
Sorry for the unsolicited feedback/suggestion. If this was intentional, feel free to disregard this ticket.

I suggest renaming all of the subdirectory markdown files to "README.md" for those directories that don't already have a README.md file. This structures the files in a manner typically found and delivers the information without the need to click another link.

## From
<img width="1344" alt="Screen Shot 2022-10-11 at 4 46 27 PM" src="https://user-images.githubusercontent.com/2738244/195195597-197a50bd-98d6-4da8-a083-8e5eb17cd1d4.png">

## To
<img width="1548" alt="Screen Shot 2022-10-11 at 4 48 06 PM" src="https://user-images.githubusercontent.com/2738244/195195321-196d8240-7232-42fe-8e41-3c8aa8cb8514.png">

**Comment by hhkitsune** [comment]
Hi @DonRichards, thanks for your feedback! 

#### A little background and explanation:
These are iterative resources expected to change over time with new contributions of updated information and new contributors participating in the development of the resources. During the grant phase, we had intended that each updated primer would have a README to record versioning information and new contributors that wouldn't fit neatly into the limited space of the primer structure. We held an event that updated primers made by groups that formed at our first workshop. These updated primers received a README. Newer primers may still be in the first version, so these didn't have README files added yet. The project team has also changed over the past year to include new contributors that only recently became oriented to administering this project, but have begun work to address its needs. The resources are overseen by members of the Data Curation network (DCN) Education Committee and they may decide to organize the repository content differently in the future.
